---
name: Fake unit test
"on":
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
  
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Normal checkout
        uses: actions/checkout@v3
      - name: Check that README.md has less lines than 10
        run: |
          A=$(wc -l <README.md)
          echo "README.md has $A lines"
          if [ $A -gt 10 ]; then
            exit 2
          fi

