---
name: Do something when queued
"on":
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  gating:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the var
        run: |
          sleep 60s
