---
name: Do something when queued
"on":
  merge_group:
    types: [checks_requested]

jobs:
  gating:
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: |
            date
    