---
name: Do something when queued
"on":
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  gating:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: |
          sleep 10s
