---
name: Do something when pull request updated
"on":
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  gating-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: |
          sleep 10s
