---
name: Do something when pull request updated
"on":
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

jobs:
  gating-pull-request:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Sleep
        run: |
          date
          sleep 10s
          date
